// Generated by jextract

package com.github.fullstorydev.grpcurl.osx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class GoSlice {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("data"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("len"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("cap")
    );
    public static MemoryLayout $LAYOUT() {
        return GoSlice.$struct$LAYOUT;
    }
    static final VarHandle data$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("data"));
    public static VarHandle data$VH() {
        return GoSlice.data$VH;
    }
    public static MemoryAddress data$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)GoSlice.data$VH.get(seg);
    }
    public static void data$set( MemorySegment seg, MemoryAddress x) {
        GoSlice.data$VH.set(seg, x);
    }
    public static MemoryAddress data$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)GoSlice.data$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void data$set(MemorySegment seg, long index, MemoryAddress x) {
        GoSlice.data$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle len$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("len"));
    public static VarHandle len$VH() {
        return GoSlice.len$VH;
    }
    public static long len$get(MemorySegment seg) {
        return (long)GoSlice.len$VH.get(seg);
    }
    public static void len$set( MemorySegment seg, long x) {
        GoSlice.len$VH.set(seg, x);
    }
    public static long len$get(MemorySegment seg, long index) {
        return (long)GoSlice.len$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void len$set(MemorySegment seg, long index, long x) {
        GoSlice.len$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle cap$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("cap"));
    public static VarHandle cap$VH() {
        return GoSlice.cap$VH;
    }
    public static long cap$get(MemorySegment seg) {
        return (long)GoSlice.cap$VH.get(seg);
    }
    public static void cap$set( MemorySegment seg, long x) {
        GoSlice.cap$VH.set(seg, x);
    }
    public static long cap$get(MemorySegment seg, long index) {
        return (long)GoSlice.cap$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void cap$set(MemorySegment seg, long index, long x) {
        GoSlice.cap$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


