// Generated by jextract

package com.github.fullstorydev.grpcurl;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;

class constants$0 {

    static final FunctionDescriptor mainExport$FUNC = FunctionDescriptor.ofVoid(
        MemoryLayout.structLayout(
            Constants$root.C_POINTER$LAYOUT.withName("data"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("len"),
            Constants$root.C_LONG_LONG$LAYOUT.withName("cap")
        )
    );
    static final MethodHandle mainExport$MH = RuntimeHelper.downcallHandle(
        "mainExport",
        constants$0.mainExport$FUNC
    );
    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
}


