// Generated by jextract

package com.github.fullstorydev.grpcurl;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class grpcurl_h  {

    /* package-private */ grpcurl_h() {}
    public static OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    public static OfLong ptrdiff_t = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfInt wchar_t = Constants$root.C_INT$LAYOUT;
    public static OfShort GoInt16 = Constants$root.C_SHORT$LAYOUT;
    public static OfInt GoInt32 = Constants$root.C_INT$LAYOUT;
    public static OfLong GoInt64 = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfLong GoInt = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfFloat GoFloat32 = Constants$root.C_FLOAT$LAYOUT;
    public static OfDouble GoFloat64 = Constants$root.C_DOUBLE$LAYOUT;
    public static OfAddress GoMap = Constants$root.C_POINTER$LAYOUT;
    public static OfAddress GoChan = Constants$root.C_POINTER$LAYOUT;
    public static MethodHandle mainExport$MH() {
        return RuntimeHelper.requireNonNull(constants$0.mainExport$MH,"mainExport");
    }
    public static void mainExport ( MemorySegment osArgs) {
        var mh$ = mainExport$MH();
        try {
            mh$.invokeExact(osArgs);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
    public static MemoryAddress NULL() {
        return constants$0.NULL$ADDR;
    }
}


