= grpcurl-java
:table-caption!:
:toc: macro

toc::[]

Example of using project panama to call grpcurl (go) from java.


== Pre-requisites

* Java 19
* Gradle 7.6 or later
* grpcurl installed as shared library
** TODO: docs for osx and linux


== Intellij setup

https://nljug.org/intellijidea/how-to-enable-java-preview-features-and-run-code-from-intellij-idea[enable preview in java compiler]


== Usage




== jextract options

    jextract --source -t com.github.fullstorydev.grpcurl \
    -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include \
    -I /usr/local/include/grpcurl \
    -l grpcurl \
    --header-class-name grpcurl_h \
    grpcurl.h

---
final class RuntimeHelper {

    private RuntimeHelper() {}
    private final static Linker LINKER = Linker.nativeLinker();
    private final static ClassLoader LOADER = RuntimeHelper.class.getClassLoader();
    private final static MethodHandles.Lookup MH_LOOKUP = MethodHandles.lookup();
    private final static SymbolLookup SYMBOL_LOOKUP;

    final static SegmentAllocator CONSTANT_ALLOCATOR =
            (size, align) -> MemorySegment.allocateNative(size, align, MemorySession.openImplicit());

    static {
        System.load("/usr/local/lib/grpcurl.dylib");
        //System.loadLibrary("grpcurl.dylib");
        SymbolLookup loaderLookup = SymbolLookup.loaderLookup();
        SYMBOL_LOOKUP = name -> loaderLookup.lookup(name).or(() -> LINKER.defaultLookup().lookup(name));
    }